version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  angular: # name of the first service
    hostname: localhost
    build: angular-client # specify the directory of the Dockerfile
    ports:
      - "80:80" # specify port forwarding

  express: #name of the second service
    build: express-server # specify the directory of the Dockerfile
    ports:
      - "3000:3000" #specify ports forwarding
    links:
      - database

  database: # name of the third service
    image: mongo # specify image to build container from
    ports:
      - "27017:27017" # specify port forwarding